osx_image: xcode11

language: objective-c
cache:
  - bundler
  - cocoapods

env:
  # Override this variable in the matrix to specify a Swift target name suffix.
  # The variable is used by `./test.sh`
  - SWIFT_SUFFIX=

matrix:
  include:
  - podfile: abtesting/Podfile
    env: SAMPLE=ABTesting
  - podfile: admob/Podfile
    env: SAMPLE=AdMob
  - podfile: analytics/Podfile
    env: SAMPLE=Analytics
  - podfile: authentication/Podfile
    env: SAMPLE=Authentication
  - podfile: config/Podfile
    env: SAMPLE=Config
  - podfile: crashlytics/Podfile
    env: SAMPLE=Crashlytics
  - podfile: database/Podfile
    env: SAMPLE=Database
  - podfile: dynamiclinks/Podfile
    env: SAMPLE=DynamicLinks
  - podfile: firestore/Podfile
    env: SAMPLE=Firestore
  - podfile: functions/Podfile
    env: SAMPLE=Functions
  - podfile: messaging/Podfile
    env: SAMPLE=InAppMessaging
  - podfile: inappmessaging/Podfile
    env: SAMPLE=Messaging
  - podfile: mlmodelinterpreter/Podfile
    env: SAMPLE=MLModelInterpreter
  - podfile: mlvision/Podfile
    env: SAMPLE=MLVision
  - podfile: performance/Podfile
    env: SAMPLE=Performance
  - podfile: storage/Podfile
    env: SAMPLE=Storage
  - podfile: installations/Podfile
    env: SAMPLE=Installations
  - podfile: installations/Podfile
    env:
      - SAMPLE=Installations
      - SWIFT_SUFFIX=Swift

before_install:
  - cd $SAMPLE
  - bundle install
  - gem install xcpretty
  - bundle exec pod install --repo-update
  - cp ../mock-GoogleService-Info.plist ./GoogleService-Info.plist
  - sed -i '' '/<key>BUNDLE_ID</{n;s/id/com.google.firebase.quickstart.${SAMPLE}Example/;}' GoogleService-Info.plist
  - gem install xcodeproj
  - ruby ../info_script.rb $SAMPLE
  - cd -
  - sed -i '' 's#DYNAMIC_LINK_DOMAIN#https://qpf6m.app.goo.gl#' dynamiclinks/DynamicLinksExample/DynamicLinksExample.entitlements
  - sed -i '' 's#YOUR_DOMAIN_URI_PREFIX";#https://qpf6m.app.goo.gl";#' dynamiclinks/DynamicLinksExample/ViewController.m
  - sed -i '' 's/REVERSED_CLIENT_ID/com.googleusercontent.apps.1025801074639-qkaflmcjc2mlfb7r5n0pda5eejdpi36t/' authentication/AuthenticationExample/Info.plist
  - sed -i '' 's/REVERSED_CLIENT_ID/com.googleusercontent.apps.1025801074639-6p6ebi8amuklcjrto20gvpe295smm8u6/' functions/FunctionsExample/Info.plist
  - ./scripts/install_secrets.sh

script: travis_retry ./test.sh

branches:
  only:
    - master
